### ISSUE TITLE
Flathub release

### ISSUE THREAD

**Issue by CactiChameleon9** [Daniele-rolli/Beaver-Notes#10]
Flathub is one of the easiest ways for a Linux systems to get apps - working across basically every major distro (with easy updates)

It would be nice to see Beaver Notes on flathub :)

**Comment by Daniele-rolli** [comment]
Thanks for your feedback, as mentioned in discussion #8 I'll work on flatpak support as soon as I can.

**Comment by johnblommers** [comment]
Flatpak is a great way to make updates available to the users. I check for updates to my flatpak applications at least daily. 

Now if your AppImage has enabled automatic updates that would be good to know. That's how I've installed Beaver Notes.

**Comment by CactiChameleon9** [comment]
> Thanks for your feedback, as mentioned in discussion #8 I'll work on flatpak support as soon as I can.

Ah, sorry - I forgot to search discussion for flatpak. I am glad it is on your radar :)
