### ISSUE TITLE
New Note > Add title > Clicking enter and or numpad enter does not "focus note"

### ISSUE THREAD

**Issue by grand-lotus-iroh** [Daniele-rolli/Beaver-Notes#101]
**Is your feature request related to a problem? Please describe.**
When I create a note, I'm unable to hit enter to focus on note section when I type a Note title. Instead, I have to hit tab.

**Describe the solution you'd like**
When I press numpad enter or enter button it acts as if I'm hitting enter...

**Describe alternatives you've considered**
N/A

**Additional context**
I believe it would be interesting to have the ability, as seen in some other note-taking applications, to include a feature for "title focus upon creating a new note." If you check out the older version of the Evernote app, it's nearly flawless, and there are some fantastic concepts to draw inspiration from. For instance, the use of double hyphens transforming into a horizontal rule is also a noteworthy and beneficial feature.

**Comment by Daniele-rolli** [comment]
Thank you for bringing this issue to our attention. The team has addressed it by merging pull request #105. Expect to see a new version of Beaver Notes soon.
