### ISSUE TITLE
Upgraded "select font" options

### ISSUE THREAD

**Issue by grand-lotus-iroh** [Daniele-rolli/Beaver-Notes#102]
**Is your feature request related to a problem? Please describe.**
I chose Avenir as my new favorite font for beaver app but the problem is, that font doesn't match the header font, I think when I choose a font in the settings it doesn't apply to everything so naturally it's going to mis-match things.

**Describe the solution you'd like**
Similar to how you can choose apps in mobile apps, like Bear or other apps, I think if you gave me more options, I'd be more excited to launch up beaver notes and take more notes!

![image](https://github.com/Daniele-rolli/Beaver-Notes/assets/1291364/78b832fa-07b6-4e34-b991-1906fe7804ab)

**Describe alternatives you've considered**
N/A

**Additional context**
Instead of limiting font selection to just the "Editor font," it would be great if I could also choose a "Header font." Additionally, incorporating operating system detection and allowing the use of fonts already installed on my PC would be convenient. For instance, I've downloaded fonts from Google Fonts on one occasion, and another time, I came across a font I adore on a different website. It would be helpful if I could simply input the desired font, similar to editing CSS with the font-family: property.

**Comment by Daniele-rolli** [comment]
Hey, could you please share some screenshots of the issue you're experiencing? I'm currently unable to reproduce the issue. Regarding the option of extracting fonts from the system, I will certainly consider it. However, allowing the app to access every font from the system might be cumbersome and potentially detrimental to the user experience.

**Comment by grand-lotus-iroh** [comment]
You know what, it's fixed. I re-picked from the dropdown and everything matches.
