### ISSUE TITLE
Add the option to organize notes in a sidebar.

### ISSUE THREAD

**Issue by HeliusHao** [Daniele-rolli/Beaver-Notes#125]
thanks
![Snipaste_2024-02-22_12-20-13](https://github.com/Daniele-rolli/Beaver-Notes/assets/33107305/b717f600-4c87-476d-abb2-959ff5d8976c)

**Comment by Daniele-rolli** [comment]
Hey there, thanks for your suggestion. I'll add it to our roadmap; however, the feature might take some time to be developed as we are also working on Beaver Pocket.

**Comment by Daniele-rolli** [comment]
Hey there again, thanks for sharing your insight regarding using a sidebar doe organizing notes. I appreciate your engagement with the project and your desire to enhance its functionality. However after a carful consideration and in line with our project's design philosophy, we've opted to keep a card-based layout to maximize the visibility and accessibility of notes. While I understand the appeal of a sidebar for some users, implementing it would deviate from our current design direction and could potentially introduce complexities that might compromise the simplicity and efficiency of beaver's interface. That said, I'm grateful for your input and I encourage you to continue sharing your ideas with us. Thanks again for your feedback.
