### ISSUE TITLE
Syncing note written yesterday on another device

### ISSUE THREAD

**Issue by JVimes** [Daniele-rolli/Beaver-Notes#140]
**Question or Assistance Request**

**Description**

A note written yesterday on another device didn't import. Is this supported?
I notice export produces a new, dated directory each day. That seems to have something to do with it.

**Environment (if applicable)**
- Operating System: Windows
- Version of the project : v2.8.0

**Comment by Daniele-rolli** [comment]
Thanks for pointing that out. The sync is built to only sync data from the current date to avoid overwriting. This was done in the earlier versions of Beaver Notes. However, I believe we could fix the issue by checking if the current day's export is available, and if it is not, then fetch the data from the day before.

**Comment by Daniele-rolli** [comment]
It's fixed! Beaver now imports data from the most recent available date, iterating backward through dates until it finds a suitable directory with data. Expect this fix to be released in version 3.0.0.

**Comment by JVimes** [comment]
That's great, thanks! 🎉
