### ISSUE TITLE
Toolbar scrolls when there's enough space

### ISSUE THREAD

**Issue by JVimes** [Daniele-rolli/Beaver-Notes#142]
**Bug Description**
The toolbar scrolls when the window is wide enough to fit all the tools. 

![image](https://github.com/Daniele-rolli/Beaver-Notes/assets/6148201/c32c2059-17eb-462d-b29f-3bfb283a7764)

**Desktop (please complete the following information):**
- OS: Windows 10
- Application Version: 2.9.0 (yay!)

**Comment by Daniele-rolli** [comment]
Thanks for reporting this bug. I've proceeded to fix this in commit https://github.com/Daniele-rolli/Beaver-Notes/commit/1518b1132efc316ac3573a18fbcc17d6fa7594f5
