### ISSUE TITLE
Cursor in URL Input field

### ISSUE THREAD

**Issue by JVimes** [Daniele-rolli/Beaver-Notes#143]
**Is your feature request related to a problem? Please describe.**

When hyperlinking text, it's overwritten if user forgets to click in the input field before pressing Ctrl+V. Also, a mouse move/click can be removed from the workflow.

**Describe the solution you'd like**

When this pop-up appears, I'd suggest placing keyboard focus into the Input field. Then user can hyperlink more easily.

![image](https://github.com/Daniele-rolli/Beaver-Notes/assets/6148201/d317e0ec-3e24-429e-8e11-c06c02e9669d)

I'd suggest this workflow:

1. Select text
2. Click 🔗 (or Ctrl+K)
3. Ctrl+V pastes URL
4. Enter closes with changes, Esc closes discarding changes.

**Comment by Daniele-rolli** [comment]
Thanks for the insight. I've made some changes in commit https://github.com/Daniele-rolli/Beaver-Notes/commit/1518b1132efc316ac3573a18fbcc17d6fa7594f5. Now, input fields are automatically focused, and pressing enter saves the changes, while pressing esc doesn't. I'm still working on making them close the pop-up.

**Comment by Daniele-rolli** [comment]
The last commit now allows the user to press Enter to save changes and Esc to close the input without saving. Moreover, inputs are now unfocused, and if, for whatever reason, they are not, you can simply press Ctrl or Cmd + L to focus the input field. Thanks again for your feedback; I hope this is enough to fix the issue.
