### ISSUE TITLE
Hyperlink issue

### ISSUE THREAD

**Issue by JVimes** [Daniele-rolli/Beaver-Notes#151]
**Bug Description**
When I use the hyperlink tool, the URL pop-up doesn't appear. If I click it again, then the pop-up appears and won't close.

**To Reproduce**

https://github.com/Daniele-rolli/Beaver-Notes/assets/6148201/6ca0d0b3-b87b-4c0e-a53d-81b987f8e318

**Desktop (please complete the following information):**
- OS: Windows 10
- Application Version: v3.0.0

**Comment by Daniele-rolli** [comment]
It's rather odd. I'll look into it and fix it. Thanks for reporting this issue.

**Comment by Daniele-rolli** [comment]
I've reverted the modifications made in version 3.0.0. Now links open normally, and you can focus the input field by pressing mod+l. Pressing enter will save the value but won't close the field, as it conflicts with tiptap's function. To close a field now, you need to click anywhere outside the link or move with arrow keys.
