### ISSUE TITLE
Markdown Syntax and Custom CSS Support

### ISSUE THREAD

**Issue by Dlg15** [Daniele-rolli/Beaver-Notes#16]
It seems that some common Markdown syntax, such as tables, hyperlinks, task lists, etc., does not work well in this App. Also, it should be possible to allow custom CSS or themes so that users can develop personalized styles.

**Comment by Daniele-rolli** [comment]
Thanks for you feedback. This application, like many others, follows a specific markdown syntax, primarily based on its tiptap components. As for custom themes, they might deviate from the app's core goal of maintaining a minimal and clutter-free interface, so they're not a goal as of now.

**Comment by Dlg15** [comment]
I'm sorry for adding another comment to the closed issue.  I'm not sure how to use the specific Markdown syntax in this App. I inserted a hyperlink and a table using the standard Markdown syntax, as seen in the following figure, but they are still shown as plain text and not in the desired target style. Is there something wrong with my input?
![image](https://github.com/Daniele-rolli/Beaver-Notes/assets/145707493/05cdf21f-a6cf-44ba-8ade-040af71e3d33)

**Comment by Daniele-rolli** [comment]
Your input is totally fine, but Beaver Noted doesn’t support tables or the markdown syntax for links as they are not implemented in tiptap. I hope this doesn’t cause much trouble on your end.

**Comment by Dlg15** [comment]
Thanks for your reply. Hopefully these markdown syntaxes will soon be supported by Beaver Notes, which I am sure will give users a better writing experience. I'll keep an eye on the App.
