### ISSUE TITLE
Feature request: Text Colour and Portable Mode

### ISSUE THREAD

**Issue by SullieLore** [Daniele-rolli/Beaver-Notes#164]
**Is your feature request related to a problem? Please describe.**
- I use an OLED screen, so white text on a black/dark background looks intense.
- I prefer not to have installed programs to ensure the settings can be kept with the application.

**Describe the solution you'd like**
- A grey/slight yellow text would be ideal or give users the option of choosing default text colour.
- Advanced option of where to keep settings files and/or release standalone Beaver-notes.exe in GitHub releases.

**Describe alternatives you've considered**
- Using a different app.
- Changing the colour profile/brightness of my display, but then this causes other issues with games/programs etc.
- Using workarounds to keep settings files together, but this is less than ideal especially when using multiple computers.

**Additional context**
Seems like a promising application. Thanks for making it. Great to see an iOS version, too.

**Comment by Daniele-rolli** [comment]
Thanks for the feedback. I'll delay version 3.1.0 and make some fixes. As far as OLED is concerned, although I don't have a device to test it on, I'll add a toggle in settings that changes the text color to a grayish shade to make it easier on the eyes. As for the portable .exe, it's just a matter of packaging, and it should be fairly simple. I'll try to push a commit in the next couple of days. If you could test it and give me some feedback on the OLED side of things, it would be brilliant.

**Comment by Daniele-rolli** [comment]
I've pushed a commit to the development branch that addresses the OLED issues by adding a toggle in settings called 'Clear Font,' which turns the text into a gray shade in dark mode. As for the portable .exe, I've tested it and it does work, but it still stores data under the same path as the app. This might be just me not knowing enough about how Windows portables work, but it seems like having the app installed or using a portable version has the same outcome. That being said, I might be wrong.

**Comment by Daniele-rolli** [comment]
I figured it out. Now, when Beaver Notes is used as a portable .exe, it saves all the data in a folder called 'data' right next to the executable.

**Comment by Daniele-rolli** [comment]
A toggle for OLED mode has been added to version 3.1.0 along with portable mode. Thanks again for your suggestion.

**Comment by SullieLore** [comment]
I have tested out 3.1.1. Excellent job with the portable mode and OLED display setting--the new text colour better matches your bear icon's background, so it fits the brand.

Couple other quick things I noticed:

1. Hidden Menu Bar is helpful, but perhaps pressing alt could toggle the menu bar? Alt actually does highlight file when the menu bar is visible, but appears to have no functionality when the bar is hidden.
2. Spellcheck English could be expanded to include EU, AU, etc.
3. When highlighting text it looks quite washed out--perhaps this is from the OLED mode? I've attached a screenshot for reference.
![Screenshot 2024-04-27 232423](https://github.com/Daniele-rolli/Beaver-Notes/assets/12578876/33bedae8-3778-41a8-9220-167eefcf3119)
4. In the Notes pane, I think that some expansion of the tags system would be useful. For instance, you could grey out unselected notes/minimise them, instead of hiding them altogether. The search pane could show key words highlighted, as it's unclear if the search is actually working, and CTRL+F could also be hidden when performing a search so it doesn't look like a user instruction to commence the search once a term has already been written. I'll add another image just in case this is difficult to parse.
![image](https://github.com/Daniele-rolli/Beaver-Notes/assets/12578876/6c9f7a9c-631b-41e6-9193-fea634bd6f32)

Hope it helps. Looking good!
