### ISSUE TITLE
Cannot Create Tags in Note Editor

### ISSUE THREAD

**Issue by saltecaramel** [Daniele-rolli/Beaver-Notes#169]
**Bug Description**
When trying to create a tag in the note, a popup saying "Add <tag-name>" shows up but hitting Enter or clicking on the popup does nothing. 

**To Reproduce**
1. Open a new note
2. Press `#` to create a new tag and enter the name of the tag
3. Press `Enter` to add the tag

**Expected Behavior**
When adding a tag, it should add the tag. 

**Screenshots**
[beavernotes-tags.webm](https://github.com/Daniele-rolli/Beaver-Notes/assets/128203216/ea4764c3-cf32-488d-9b4b-d03c5fea397a)

**Desktop (please complete the following information):**
- Device Specification: Intel i5-9600KF, NVIDIA GeForce RTX 2060
- OS: Ubuntu 22.04.4
- Application Version: 3.1.0 Flatpak

**Comment by Daniele-rolli** [comment]
Thanks again for reporting this issue. I've already released version 3.1.1 to address this issue. Thanks again for your patience.
