### ISSUE TITLE
Make the inline code more visible plus more efficient

### ISSUE THREAD

**Issue by tio-trom** [Daniele-rolli/Beaver-Notes#17]
Here's how the inline code looks like with the dark theme on:

![2023-09-24_22-16](https://github.com/Daniele-rolli/Beaver-Notes/assets/38043315/290dcaba-d3af-4a63-a080-8a396dc73e4d)
Not very visible at all. It should be a lot more obvious.

On top of that I think is a great idea to contain the code somehow so when I double click it I can select it all without selecting anything else, to be able to use that code (copy it).

**Comment by Daniele-rolli** [comment]
The inline code is considered part of the text, much like a bold phrase would be, so selecting it without selecting everything else isn't really an option. The background issue, though, is a real one and will be fixed as soon as possible. As of now, I'm prioritizing the development of Beaver Notes Pocket, but I'll look into it.
