### ISSUE TITLE
Huge zoom on focus mode

### ISSUE THREAD

**Issue by FedericoCalzoni** [Daniele-rolli/Beaver-Notes#171]
**Bug Description**
When focus mode is toggled, a huge zoom to the note is applied.

**To Reproduce**
1. Click on focus mode

**Expected Behavior**
See my note

**Screenshots**
This is a letter V
![image](https://github.com/Daniele-rolli/Beaver-Notes/assets/56981117/159c2605-64c2-45b0-a907-3ef4e54751b3)

**Desktop (please complete the following information):**
## Software Information:
- **Firmware Version:**                            1.13.0
- **OS Name:**                                     Arch Linux
- **OS Type:**                                     64-bit
- **GNOME Version:**                               46
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.8.7-arch1-2

**Comment by Daniele-rolli** [comment]
Thanks for reporting the issue. I believe I know what went wrong. Try going to settings and setting the interface size to default; this should fix the issue. Let me know if it worked, and I’ll make sure to fix it in the next version.

**Comment by FedericoCalzoni** [comment]
It was already to default. But changing it to something else and than again switching back to default seems to fix the issue.

**Comment by FedericoCalzoni** [comment]
Thanks for your work!
