### ISSUE TITLE
Tabbing to indent a bullet indents text but not bullet

### ISSUE THREAD

**Issue by barry-denby** [Daniele-rolli/Beaver-Notes#172]
Prior to V3.1.0 if markdown formatting was used to write a ordered or bulleted list should you wish to indent it you could do so by pressing the tab key. e.g. writing a mark down list with the second line indented would look similar to this

- no indent
    - indent
 
Now however in V3.1.0 if you do this is looks like

- no indent
-     indent

where the bullet is on the same indent level when it should be immediately left of indent.

The tabbing behavior works correctly with checklists however. Shift + Tab also correctly decreases the indent

To recreate this in a note do the following

1) type "- no indent" to start a new bullet list
2) on the next line after the bullet has appeared hit tab and then write the second line. The text has moved but the bullet has not.

**Comment by Daniele-rolli** [comment]
Thanks for your feedback! I've already fixed the issue in commit 208f0b4. I believe it went unnoticed during the development of the literal tab extension, and nobody noticed that it didn't work properly with lists until now. That said, the fix will be included in the upcoming new release.

https://github.com/Daniele-rolli/Beaver-Notes/assets/67503004/1ec8813f-fd36-435d-bbbc-607f4e4156d0
