### ISSUE TITLE
How is Markdown working?

### ISSUE THREAD

**Issue by tio-trom** [Daniele-rolli/Beaver-Notes#18]
I am looking for a simple app to move my markdown notes to but if I copy the markdown text from my notes Beaver does not understand any of them:

![2023-09-24_22-20](https://github.com/Daniele-rolli/Beaver-Notes/assets/38043315/5f4524dc-0591-46b0-9385-df213ab22758)

I am a bit confused :D

**Comment by Daniele-rolli** [comment]
I get it might seem a bit confusing if you copy and paste the markdown right into the note. Beaver Notes won't be able to read it as, unfortunately, tiptap, the editor library, isn't very flexible in understanding markdown if not written directly in the app

**Comment by tio-trom** [comment]
Ahh I understand...so copy pasting won't work. Do you think this is something that will be improved? Is that library maintained by you as well?

**Comment by Daniele-rolli** [comment]
I personally don't have the skills to maintain the library. Besides, it's a well-known project supported by big tech companies, as their services rely on it. I'll see what I can do, but I can't guarantee anything when it comes to copying and pasting.

**Comment by tio-trom** [comment]
Could there be a way to "refresh" the pasted content as if it is written? Idk I am just saying, but I have no clue how this works. I wish it worked because I have so many markdown notes and copy pasting them would have been a breeze.

**Comment by Daniele-rolli** [comment]
You could just rewrite the ‘’’ at the end of the code to make it a code block, the same for every other component. For the record, this issue happens because tiptap stores everything in a labeled category, and everything pasted in is either text or not. This should exclude rich text, which maintains its formatting when copied, and obviously images.

**Comment by tio-trom** [comment]
I understand but it is quite a lot of work....I have hundreds of code snippets....Will see about it ;)

**Comment by Daniele-rolli** [comment]
Yeah, sorry about that. I hope this doesn't make you love the project any less.

**Comment by tio-trom** [comment]
hehe nope I so appreciate this app and your efforts! So far looks really great and I am more convinced to add this as our default note taking app to TROMjaro.
