### ISSUE TITLE
Clicking any links does not work

### ISSUE THREAD

**Issue by tio-trom** [Daniele-rolli/Beaver-Notes#19]
I get this error:

![2023-09-24_22-25](https://github.com/Daniele-rolli/Beaver-Notes/assets/38043315/c5147c26-729e-4a3f-a00b-3e05577f1e28)

I am using Version 0.0.8

**Comment by Daniele-rolli** [comment]
So, I've looked into the issue and was able to open the link just fine. This issue might be related to the operating system you are using or the way you installed Beaver Notes.

**Comment by tio-trom** [comment]
> So, I've looked into the issue and was able to open the link just fine. This issue might be related to the operating system you are using or the way you installed Beaver Notes.

I should have included more details I apologize. I am using Arch Linux , Beaver Notes 0.0.8. Installed from AUR - https://aur.archlinux.org/packages/beaver-notes-bin

It is basically using the .rpm package.

**Comment by Daniele-rolli** [comment]
Probably the way Arch handles AUR packages prevents it from having access to the system's browser.

**Comment by tio-trom** [comment]
Interesting...I tried the appimage too and the same issue. I have not seen this issue before in Arch.

**Comment by Daniele-rolli** [comment]
I've tried the same thing on my Debian desktop, and the link opened smoothly. It's possible that the system doesn't grant browser access to certain apps, or it might be attempting to open the link with a different browser.

**Comment by tio-trom** [comment]
Ok I think I figured it. If the text is bold the links seem to not work. Can you test please? So make a bold text and add a link to it.

**Comment by Daniele-rolli** [comment]
Yep, you are right. It doesn't even let me open it. Besides, who really needs bold links.

**Comment by tio-trom** [comment]
Maybe you can fix it? At times you may write some text in bold and add a link to it....so others will encounter this issue too.

**Comment by Daniele-rolli** [comment]
I’m afraid I cannot fix this issue as it’s related to tiptap’s behavior. This issue might be marked as ‘won’t fix,’ but the upside is that it’s very rare for someone to make bold text a link.

**Comment by tio-trom** [comment]
Ok I understand
