### ISSUE TITLE
Notes cards - text out of the box

### ISSUE THREAD

**Issue by tio-trom** [Daniele-rolli/Beaver-Notes#20]
Here:

![2023-09-24_22-30](https://github.com/Daniele-rolli/Beaver-Notes/assets/38043315/23eea0b6-917c-42da-904f-dc4784ccdbd2)

We need to contain that :)

**Comment by Daniele-rolli** [comment]
Hey, thanks for opening so many issues. I see you've taken a particular interest in the project. I took the liberty of copying the content of the photo, and it indeed goes beyond the note. However, this behavior seems to be linked to the link you are using. I've tried with multiple other links and wasn't able to recreate the issue.

**Comment by tio-trom** [comment]
I am one of the developers of TROMjaro Linux https://www.tromjaro.com and I would love to add a new Notes app as default to our distro. So far I love your work and I am keen to test it in detail and report bugs. I will try not to overwhelm you.

As for the bug, did you try it with very lenghty links?

**Comment by Daniele-rolli** [comment]
Okay, so after looking into it, apparently the cards don't handle absurdly long links well. I'll investigate the code and see what I can fix.

<img width="796" alt="Screenshot 2023-09-24 at 10 51 26 PM" src="https://github.com/Daniele-rolli/Beaver-Notes/assets/67503004/ac416ef4-6954-4531-87bd-70968173088d">
<img width="962" alt="Screenshot 2023-09-24 at 10 51 35 PM" src="https://github.com/Daniele-rolli/Beaver-Notes/assets/67503004/e3f11f8b-d16b-4696-9da8-8a4d5b223d7d">

**Comment by Daniele-rolli** [comment]
So, I've fixed the text going out of the card by adding 'overflow-hidden' to the cards' CSS. I'll release this fix along with version 1.0 if it's okay with you, and I'll also proceed to close the issue.

**Comment by tio-trom** [comment]
You're awesome! Thank you. I will close it now.
