### ISSUE TITLE
Code block dropdown menu overlaps with the code

### ISSUE THREAD

**Issue by tio-trom** [Daniele-rolli/Beaver-Notes#21]
Here:

![2023-09-24_23-28](https://github.com/Daniele-rolli/Beaver-Notes/assets/38043315/1a81f282-560e-481f-a1e2-6b1abb81a860)

Maybe put the dropdown above the code block.

**Comment by Daniele-rolli** [comment]
That’s a tricky one. I’ve tried to fix it multiple times, but in the end, I just figured I could press Enter, move the piece of code to the bottom row, and go on with my life.

**Comment by tio-trom** [comment]
Why not add a top padding for the text that's inside a code block? Or margins for the dropdown menu?

**Comment by tio-trom** [comment]
![2023-09-24_23-40](https://github.com/Daniele-rolli/Beaver-Notes/assets/38043315/f628bdd6-1024-43ef-8777-b168906cbe45)

Make it display: block and add a top margin of 25px.

**Comment by Daniele-rolli** [comment]
Well, it’s pretty hard to style the content of a component. You can style the component itself, but not the content. Damn, Tiptap seemed more customizable.

**Comment by Daniele-rolli** [comment]
Ok, I was wrong, it seems solvable. Let me just write down a few lines of code, and this fix will be a part of version 1.0.

**Comment by Daniele-rolli** [comment]
We can declare this case closed. The padding has been fixed

<img width="1512" alt="Screenshot 2023-09-24 at 11 47 31 PM" src="https://github.com/Daniele-rolli/Beaver-Notes/assets/67503004/49e7cd29-b95a-4e12-bc3e-490d9de0d2cd">

<img width="813" alt="Screenshot 2023-09-24 at 11 47 42 PM" src="https://github.com/Daniele-rolli/Beaver-Notes/assets/67503004/ff687338-86d9-408f-9455-a442bfdf1106">
