### ISSUE TITLE
Font size does not change

### ISSUE THREAD

**Issue by tio-trom** [Daniele-rolli/Beaver-Notes#23]
In Linux (AUR or Appimage) changing the font size in the settings will not change the font size anywhere.

**Comment by Daniele-rolli** [comment]
Thanks for pointing that out. I was actually aware of that issue, and I'm working on a fix for version 1.0. However, with the development of the mobile app, I've been very busy.

**Comment by Daniele-rolli** [comment]
After careful consideration, I've decided to remove the font size switcher as the app already adapts to device settings. Thanks for understanding.
