### ISSUE TITLE
Paste image from clipboard

### ISSUE THREAD

**Issue by tio-trom** [Daniele-rolli/Beaver-Notes#24]
Is there any way to support pasting an image from clipboard?

**Comment by Daniele-rolli** [comment]
Well, you could try dragging and dropping it in. Otherwise, try saving the image to your device’s storage, in a place accessible such as your desktop, and then drag and drop it into Beaver.

**Comment by tio-trom** [comment]
Ok but copy pasting an image is so useful. Maybe leave this open in case you can implement it in the future?

**Comment by Daniele-rolli** [comment]
I've implemented coping images from the clipboard along with fixing the other issues in version 1.0.0
