### ISSUE TITLE
Import using snap on Ubuntu 23.04 does has encoding issues

### ISSUE THREAD

**Issue by IvoLimmen** [Daniele-rolli/Beaver-Notes#3]
When using the snap version of Beaver notes the installation on Ubuntu 23.04 works.

Application is usable but importing notes dialog show the following:
![image](https://github.com/Daniele-rolli/Beaver-Notes/assets/196375/06422062-c719-42a0-ac65-9dc1cc23da71)

Either the font that used is substituted by a WingDing like variant or a wrong encoding is used.

OS:
Ubuntu 23.04
Uname -a: Linux QSD 6.2.0-26-generic #26-Ubuntu SMP PREEMPT_DYNAMIC Mon Jul 10 23:39:54 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

Machine:
Dell Inc. XPS 15 9570
NVIDIA GeForce GTX 1050 Ti with Max-Q Design / Intel® UHD Graphics 630 (CFL GT2)

Windowing system: Wayland
GNOME version: 44.3

**Comment by Daniele-rolli** [comment]
I appreciate your understanding. As soon as I have access to a Linux machine, I'll look into this. I apologize for any inconvenience, and I assure you that I'll fix it, while also introducing the sync feature in version 0.0.7.
