### ISSUE TITLE
Why is a note app nearly 500MB??

### ISSUE THREAD

**Issue by ultratiem** [Daniele-rolli/Beaver-Notes#34]
Check your builds, pretty sure you don't need these in every one:
![Screenshot 2023-11-26 at 8 59 12 AM](https://github.com/Daniele-rolli/Beaver-Notes/assets/2991193/d6947522-e34c-4836-b83f-731cead5be63)

Also, Electron is a gaping security hole and a pig on resources. Consider moving to Swift, just saying.

**Comment by Daniele-rolli** [comment]
I understand your perspective, and I will revise the building process to slim down the app. Regarding Electron, I honestly haven't noticed any resource issues. I use it on both an M1 Pro machine and an i5 4th gen, and it runs smoothly on both without a significant impact on battery life. As for Swift, using it would limit the app to Apple devices, which wouldn't be suitable for users who already use and enjoy Beaver on Linux or Windows.

**Comment by ultratiem** [comment]
Relevant: https://stackoverflow.com/questions/47597283/electron-package-reduce-the-package-size

Your app runs smooth on an i5 because it's a note app. I could run it fine on a Pentium PII, because, it's a note app.

In any case, your project, but again, 500MB for a note app is wild. Especially considering the exe is 250KB! Because, again, it's a note app.

**Comment by Daniele-rolli** [comment]
Thanks for the insights and the link. I'll look into it and report back if I manage to make the app any lighter.

**Comment by Daniele-rolli** [comment]
I've cleaned up some dependencies, and guess what? The app size has almost halved!

<img width="274" alt="Screenshot 2023-11-26 at 8 26 10 PM" src="https://github.com/Daniele-rolli/Beaver-Notes/assets/67503004/3f19f490-0c61-425b-9192-2853e8a8bcf7">
