### ISSUE TITLE
Mac app doesn't start

### ISSUE THREAD

**Issue by lizaaaa900** [Daniele-rolli/Beaver-Notes#36]
Downloaded the application from the website for my MacOS operating system.
Can't start it. Crashes instantly.
My os: Mac OSX 14.0 (Intel)

**Comment by Daniele-rolli** [comment]
Hey there, would you mind sharing the crash log if any is displayed? Thanks. I’ll work on fixing it promptly.

**Comment by rexzhang** [comment]
macOS 12(intel)
```
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Incident Identifier: FE2B289C-F63B-4142-AC4F-CA93BB3D145C
CrashReporter Key:   A579D432-2FE8-A396-632B-DC7FA7EEB972
Hardware Model:      MacBookPro12,1
Process:             Beaver-notes [87155]
Path:                /Applications/Beaver-notes.app/Contents/MacOS/Beaver-notes
Identifier:          com.danielerolli.beaver-notes
Version:             2.2.2 (2.2.2)
Code Type:           X86-64 (Native)
Role:                Default
Parent Process:      launchd [1]
Coalition:           com.danielerolli.beaver-notes [47677]

Date/Time:           2023-12-21 20:00:29.5099 +0800
Launch Time:         2023-12-21 20:00:29.3113 +0800
OS Version:          macOS 12.7.2 (21G1974)
Release Type:        User
Report Version:      104

Exception Type:  EXC_CRASH (SIGKILL (Code Signature Invalid))
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Reason: CODESIGNING 1 

Triggered by Thread:  0

Thread 0 Crashed:
0                                	       0x10d967ae0 _dyld_start + 0
1   ???                           	       0x10a791000 ???


Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x00007ff7b576ebd8
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x000000010d967ae0  rfl: 0x0000000000000200  cr2: 0x0000000000000000
  
Logical CPU:     0
Error Code:      0x00000000 
Trap Number:     0


Binary Images:
       0x10d963000 -        0x10d9cefff  (*) <499010ac-3054-326e-a050-fefffb5ce89a> 
       0x10a791000 -        0x10a7e0fff ??? (*) <ab3cb5d1-eb3f-388f-8c63-416a00da1aaa> ???

Error Formulating Crash Report:
dyld_process_snapshot_get_shared_cache failed

EOF

-----------
Full Report
-----------

{"app_name":"Beaver-notes","timestamp":"2023-12-21 20:00:29.00 +0800","app_version":"2.2.2","slice_uuid":"ab3cb5d1-eb3f-388f-8c63-416a00da1aaa","build_version":"2.2.2","platform":0,"bundleID":"com.danielerolli.beaver-notes","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 12.7.2 (21G1974)","incident_id":"FE2B289C-F63B-4142-AC4F-CA93BB3D145C","name":"Beaver-notes"}
{
  "uptime" : 320000,
  "procLaunch" : "2023-12-21 20:00:29.3113 +0800",
  "procRole" : "Default",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookPro12,1",
  "procStartAbsTime" : 329011787303496,
  "coalitionID" : 47677,
  "osVersion" : {
    "train" : "macOS 12.7.2",
    "build" : "21G1974",
    "releaseType" : "User"
  },
  "captureTime" : "2023-12-21 20:00:29.5099 +0800",
  "incident" : "FE2B289C-F63B-4142-AC4F-CA93BB3D145C",
  "bug_type" : "309",
  "pid" : 87155,
  "procExitAbsTime" : 329011985316140,
  "cpuType" : "X86-64",
  "procName" : "Beaver-notes",
  "procPath" : "\/Applications\/Beaver-notes.app\/Contents\/MacOS\/Beaver-notes",
  "bundleInfo" : {"CFBundleShortVersionString":"2.2.2","CFBundleVersion":"2.2.2","CFBundleIdentifier":"com.danielerolli.beaver-notes"},
  "storeInfo" : {"deviceIdentifierForVendor":"63E77751-0B94-5579-A4B4-F5AF64D95247","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "com.danielerolli.beaver-notes",
  "crashReporterKey" : "A579D432-2FE8-A396-632B-DC7FA7EEB972",
  "wakeTime" : 853,
  "sleepWakeUUID" : "728627E3-F73E-4B06-9E30-5F75FB7FD2FB",
  "sip" : "enabled",
  "isCorpse" : 1,
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGKILL (Code Signature Invalid)"},
  "termination" : {"namespace":"CODESIGNING","flags":66,"code":1},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":3012777,"threadState":{"r13":{"value":0},"rax":{"value":0},"rflags":{"value":512},"cpu":{"value":0},"r14":{"value":0},"rsi":{"value":0},"r8":{"value":0},"cr2":{"value":0},"rdx":{"value":0},"r10":{"value":0},"r9":{"value":0},"r15":{"value":0},"rbx":{"value":0},"trap":{"value":0},"err":{"value":0},"r11":{"value":0},"rip":{"value":4522932960,"matchesCrashFrame":1},"rbp":{"value":0},"rsp":{"value":140701878119384},"r12":{"value":0},"rcx":{"value":0},"flavor":"x86_THREAD_STATE","rdi":{"value":0}},"frames":[{"imageOffset":19168,"symbol":"_dyld_start","symbolLocation":0,"imageIndex":0},{"imageOffset":0,"imageIndex":1}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4522913792,
    "size" : 442368,
    "uuid" : "499010ac-3054-326e-a050-fefffb5ce89a",
    "path" : "\u0004",
    "name" : "\u0004"
  },
  {
    "size" : 327680,
    "arch" : "x86_64",
    "source" : "P",
    "base" : 4470673408,
    "uuid" : "ab3cb5d1-eb3f-388f-8c63-416a00da1aaa"
  }
],
  "vmSummary" : "ReadOnly portion of Libraries: Total=980K resident=0K(0%) swapped_out_or_unallocated=980K(100%)\nWritable regions: Total=8192K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=8192K(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nSTACK GUARD                       56.0M        1 \nStack                             8192K        1 \nVM_ALLOCATE                          8K        2 \n__DATA                              32K        2 \n__DATA_CONST                        80K        1 \n__LINKEDIT                         240K        3 \n__TEXT                             752K        2 \n===========                     =======  ======= \nTOTAL                             65.1M       12 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "6112dda2fc54bc3389840642",
      "factorPackIds" : {
        "SIRI_DICTATION_ASSETS" : "620aec83b02b354d3afd2f50"
      },
      "deploymentId" : 240000145
    },
    {
      "rolloutId" : "6112e14f37f5d11121dcd519",
      "factorPackIds" : {
        "SIRI_TEXT_TO_SPEECH" : "634710168e8be655c1316aaa"
      },
      "deploymentId" : 240000229
    }
  ],
  "experiments" : [

  ]
},
  "reportNotes" : [
  "dyld_process_snapshot_get_shared_cache failed"
]
}

Model: MacBookPro12,1, BootROM 486.0.0.0.0, 2 processors, Dual-Core Intel Core i5, 2.7 GHz, 8 GB, SMC 2.28f7
Graphics: Intel Iris Graphics 6100, Intel Iris Graphics 6100, Built-In
Display: DELL U2713HM, 2560 x 1440 (QHD/WQHD - Wide Quad High Definition), Main, MirrorOff, Online
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1867 MHz, 0x80AD, 0x483943434E4E4E424C54414C41522D4E5544
Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1867 MHz, 0x80AD, 0x483943434E4E4E424C54414C41522D4E5544
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x133), Broadcom BCM43xx 1.0 (7.77.111.1 AirPortDriverBrcmNIC-1710.4)
AirPort: 
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: AX88179, Ethernet, en4
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD SM0256G, 251 GB
USB Device: USB30Bus
USB Device: USB3.0 Hub
USB Device: USB3.0 Hub
USB Device: AX88179
USB Device: hub_device
USB Device: Bluetooth USB Host Controller
USB Device: USB2.0 Hub
USB Device: AirPod Case
USB Device: USB2.0 Hub
USB Device: USB Optical Mouse
USB Device: hub_device
USB Device: Realforce 87
USB Device: USB Billboard Device
Thunderbolt Bus: MacBook Pro, Apple Inc., 27.1

```

**Comment by lizaaaa900** [comment]
I was on vacation, haha. I'll try and find a crash log too.
Found it! Also, seems another person also experienced a possible crash.
Hope you can fix it  ✨

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Incident Identifier: AB8A9B14-4512-46B7-B683-33819ECD141B
CrashReporter Key:   10C707BE-1865-001F-4317-34874584DA3B
Hardware Model:      MacBookPro11,5
Process:             Beaver-notes [11780]
Path:                /Applications/Beaver-notes.app/Contents/MacOS/Beaver-notes
Identifier:          com.danielerolli.beaver-notes
Version:             2.2.2 (2.2.2)
Code Type:           X86-64 (Native)
Role:                Default
Parent Process:      launchd [1]
Coalition:           com.danielerolli.beaver-notes [6462]

Date/Time:           2023-12-19 05:02:38.7083 +0100
Launch Time:         2023-12-19 05:02:38.6163 +0100
OS Version:          macOS 14.0 (23A344)
Release Type:        User
Report Version:      104

Exception Type:  EXC_CRASH (SIGKILL (Code Signature Invalid))
Exception Codes: 0x0000000000000000, 0x0000000000000000
Termination Reason: CODESIGNING 1 Taskgated Invalid Signature

Triggered by Thread:  0

Thread 0 Crashed:
0                                 	       0x10aa6d040 _dyld_start + 0
1                                	       0x109510000 ???


Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x00007ff7b69efb88
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x000000010aa6d040  rfl: 0x0000000000000200  cr2: 0x0000000000000000
  
Logical CPU:     0
Error Code:      0x00000000 
Trap Number:     0


Binary Images:
       0x10aa68000 -        0x10ab07fff  (*) <1289b60a-4980-342d-b1a4-250bbee392f1> ???
       0x109510000 -        0x10955ffff  (*) <ab3cb5d1-eb3f-388f-8c63-416a00da1aaa> 
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???

Error Formulating Crash Report:
dyld_process_snapshot_get_shared_cache failed

EOF

-----------
Full Report
-----------

{"app_name":"Beaver-notes","timestamp":"2023-12-19 05:02:38.00 +0100","app_version":"2.2.2","slice_uuid":"ab3cb5d1-eb3f-388f-8c63-416a00da1aaa","build_version":"2.2.2","platform":0,"bundleID":"com.danielerolli.beaver-notes","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 14.0 (23A344)","roots_installed":0,"name":"Beaver-notes","incident_id":"AB8A9B14-4512-46B7-B683-33819ECD141B"}
{
  "uptime" : 36000,
  "procRole" : "Default",
  "version" : 2,
  "userID" : 502,
  "deployVersion" : 210,
  "modelCode" : "MacBookPro11,5",
  "coalitionID" : 6462,
  "osVersion" : {
    "train" : "macOS 14.0",
    "build" : "23A344",
    "releaseType" : "User"
  },
  "captureTime" : "2023-12-19 05:02:38.7083 +0100",
  "codeSigningMonitor" : 0,
  "incident" : "AB8A9B14-4512-46B7-B683-33819ECD141B",
  "pid" : 11780,
  "cpuType" : "X86-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2023-12-19 05:02:38.6163 +0100",
  "procStartAbsTime" : 36995511835535,
  "procExitAbsTime" : 36995603616114,
  "procName" : "Beaver-notes",
  "procPath" : "\/Applications\/Beaver-notes.app\/Contents\/MacOS\/Beaver-notes",
  "bundleInfo" : {"CFBundleShortVersionString":"2.2.2","CFBundleVersion":"2.2.2","CFBundleIdentifier":"com.danielerolli.beaver-notes"},
  "storeInfo" : {"deviceIdentifierForVendor":"CB9ED85E-ABDD-5A5C-ABDB-B6B4372163C5","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "com.danielerolli.beaver-notes",
  "crashReporterKey" : "10C707BE-1865-001F-4317-34874584DA3B",
  "codeSigningID" : "",
  "codeSigningTeamID" : "",
  "codeSigningFlags" : 16777216,
  "codeSigningValidationCategory" : 0,
  "codeSigningTrustLevel" : 4294967295,
  "wakeTime" : 9166,
  "sleepWakeUUID" : "E2AF9A43-788F-4907-B6DE-78FD4FAB7F8F",
  "sip" : "enabled",
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGKILL (Code Signature Invalid)"},
  "termination" : {"flags":66,"code":1,"namespace":"CODESIGNING","indicator":"Taskgated Invalid Signature"},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":307241,"threadState":{"r13":{"value":0},"rax":{"value":0},"rflags":{"value":512},"cpu":{"value":0},"r14":{"value":0},"rsi":{"value":0},"r8":{"value":0},"cr2":{"value":0},"rdx":{"value":0},"r10":{"value":0},"r9":{"value":0},"r15":{"value":0},"rbx":{"value":0},"trap":{"value":0},"err":{"value":0},"r11":{"value":0},"rip":{"value":4473671744,"matchesCrashFrame":1},"rbp":{"value":0},"rsp":{"value":140701897522056},"r12":{"value":0},"rcx":{"value":0},"flavor":"x86_THREAD_STATE","rdi":{"value":0}},"frames":[{"imageOffset":20544,"symbol":"_dyld_start","symbolLocation":0,"imageIndex":0},{"imageOffset":0,"imageIndex":1}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4473651200,
    "size" : 655360,
    "uuid" : "1289b60a-4980-342d-b1a4-250bbee392f1",
    "name" : ""
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4451270656,
    "size" : 327680,
    "uuid" : "ab3cb5d1-eb3f-388f-8c63-416a00da1aaa",
    "path" : "\u001f",
    "name" : "\u001f"
  },
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  }
],
  "vmSummary" : "ReadOnly portion of Libraries: Total=1336K resident=0K(0%) swapped_out_or_unallocated=1336K(100%)\nWritable regions: Total=8192K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=8192K(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nSTACK GUARD                       56.0M        1 \nStack                             8192K        1 \nVM_ALLOCATE                          4K        1 \n__DATA                              32K        2 \n__DATA_CONST                        32K        1 \n__DATA_DIRTY                        16K        1 \n__LINKEDIT                         384K        3 \n__TEXT                             960K        2 \nshared memory                        4K        1 \n===========                     =======  ======= \nTOTAL                             65.4M       13 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "logWritingSignature" : "42b77dc67293b36d88e964b69d4a2e5fda98f2e6",
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "60356660bbe37970735c5624",
      "factorPackIds" : {

      },
      "deploymentId" : 240000027
    },
    {
      "rolloutId" : "6246d6a916a70b047e454124",
      "factorPackIds" : {

      },
      "deploymentId" : 240000010
    }
  ],
  "experiments" : [

  ]
},
  "reportNotes" : [
  "dyld_process_snapshot_get_shared_cache failed"
]
}

Hardware
========================
Modelnaam:	MacBook Pro
Model-ID:	MacBookPro11,5
Processor:	2,5 GHz Quad-Core Intel Core i7
processors:	1
Total cores:	4
L3-cache:	6 MB
Ram:	        16 GB
Mac OS:          14.0 (23A344)

**Comment by Daniele-rolli** [comment]
Thanks for reporting this issue. I’ll be fixing it soon. It boils down to the code signing certificate expiring, as I don’t have an Apple Developer account. The easy fix is to buy Apple’s developer account, which I will do. Thanks for your understanding.

**Comment by Daniele-rolli** [comment]
I've rebuilt the packages for both macOS on Apple Silicon and x86. It should work now. I hope you'll enjoy Beaver Notes despite this tiny issue.

**Comment by lizaaaa900** [comment]
No worries! I know how development is.
Great! I just tried it. It does startup, but the screen seems to be in debug mode?
![Scherm­afbeelding 2023-12-22 om 09 30 32](https://github.com/Daniele-rolli/Beaver-Notes/assets/148849637/8594fa33-3754-46dc-b5fd-520ef02de201)
When closing the debug mode, the screen stays white/empty.

**Comment by Daniele-rolli** [comment]
Yeah, sorry about that. I forgot to reinstall the dependencies before rebuilding the package. Try downloading it now and see if it works. Sorry again for the inconvenience.

**Comment by lizaaaa900** [comment]
Success! haha 
![Scherm­afbeelding 2023-12-22 om 09 57 14](https://github.com/Daniele-rolli/Beaver-Notes/assets/148849637/2f2ee14d-59bd-43f3-aadf-fa159f1d6a11)

Great job, my friend
