### ISSUE TITLE
Make autoupdate optional 

### ISSUE THREAD

**Issue by bigshans** [Daniele-rolli/Beaver-Notes#39]
**Is your feature request related to a problem? Please describe.**
Autoupdate slow down app startup. Sometimes it fails to start due to auto update.

**Describe the solution you'd like**
Provide an option I can turn off auto update.

**Describe alternatives you've considered**
No.

**Additional context**
No.

**Comment by Daniele-rolli** [comment]
I am sorry that autoupdate is giving you a hard time. Could you share a crash log or some information about the system and hardware you are running, so I can better replicate and fix this issue?

**Comment by bigshans** [comment]
> I am sorry that autoupdate is giving you a hard time. Could you share a crash log or some information about the system and hardware you are running, so I can better replicate and fix this issue?

Well, `checkForUpdatesAndNotify` will be called twice, and the second time will wait for a long time which will effect startup of application. It might be due to the GFW, so you maybe can't reproduce. I want a feature to disable autoupdate  to avoid unnecessary requests. And I manage the software through the system package manager, so self-updates within the software don't mean much to me.

```
APPIMAGE env is not defined, current application is not an AppImage
checkForUpdatesAndNotify called, downloadPromise is null
APPIMAGE env is not defined, current application is not an AppImage
checkForUpdatesAndNotify called, downloadPromise is null
```

**Comment by Daniele-rolli** [comment]
Okay, I'll keep that in mind, and I assure you the next version will have auto-updates turned off by default. Thanks for reporting that issue. By the way, when you say GFW you mean The Great Firewall, right?

**Comment by bigshans** [comment]
> Okay, I'll keep that in mind, and I assure you the next version will have auto-updates turned off by default. Thanks for reporting that issue. By the way, when you say GFW you mean The Great Firewall, right?

Yes.
