### ISSUE TITLE
Configure folder instead of importing/exporting notes

### ISSUE THREAD

**Issue by IvoLimmen** [Daniele-rolli/Beaver-Notes#4]
I like the application a lot but I would love to see a configurable folder for the notes so that I can I can sync the directory to other machines.

**Comment by Daniele-rolli** [comment]
We are working on something similar. I'm attempting to implement an automatic sync mechanism by creating a folder you can place in a cloud or SyncThing instance. I'll keep you posted on the progress.

**Comment by tio-trom** [comment]
So where are the notes stored?

**Comment by IvoLimmen** [comment]
As plain text files in the folder.

**Comment by tio-trom** [comment]
Sorry, what folder? I checked in `/home/tio/.config/Beaver-notes/` even in the Synch path folder. I cannot seem to find the files.

**Comment by steam3d** [comment]
@tio-trom I also have the same question. I set a folder path in settings and the folder is always empty.

**Comment by Daniele-rolli** [comment]
Hi there, folks! I've noticed that many of you are struggling with understanding how the sync feature works. After setting the path in the settings, you'll need to click the export or import buttons on the sidebar to copy your notes to the specified directory, as explained in the last paragraph of the documentation: [link to the documentation](https://danieles-organization.gitbook.io/beaver-notes/user-guides/set-up-the-sync), where it says, "Now, all you need to do is click 'Export' in the sidebar before closing the app, and remember to toggle 'Import' as soon as you open it." I hope this clarifies things!

**Comment by steam3d** [comment]
@Daniele-rolli For Windows Export Import buttons in left side bar do not work. In the settings those buttons work.

**Comment by Daniele-rolli** [comment]
That's odd; I've never had issues on Linux or MacOS. I'll fire up a Windows VM and check. In the meantime, what version of Beaver are you using? Some of them have issues with the export and import features.

**Comment by steam3d** [comment]
2.2.2

I clicked on the buttons in left side bar nothing happens, but when click in settings page the folder picker appears.

**Comment by Daniele-rolli** [comment]
Ok, so I've checked on a Windows VM, and everything seems to run smoothly. To solve this issue, you could either reselect the path in settings or provide some screenshots so I can better understand the problem. Alternatively, you could click Ctrl + Shift + I, select 'Console,' and then try to export the data using the arrows in the sidebar. If something fails, you should get an error message, which will help us sort out this issue.

**Comment by steam3d** [comment]
@Daniele-rolli  I seemed figure out. You need to add some popup or notification that export import were finished.  The buttons work but there is no any UI element that help understand that process finished.

**Comment by Daniele-rolli** [comment]
I'm happy you've figured it out. As far as the UI is concerned, I'll keep in mind to add a prompt to show if the import or export has been successful or not in the next version.

**Comment by Dialga** [comment]
> Sorry, what folder? I checked in `/home/tio/.config/Beaver-notes/` even in the Synch path folder. I cannot seem to find the files.
> 
> Note: I am using Linux

Did you find the answer? I also can't find where my notes are stored, without configuring sync.

**Comment by bigshans** [comment]
> > Sorry, what folder? I checked in `/home/tio/.config/Beaver-notes/` even in the Synch path folder. I cannot seem to find the files.
> > Note: I am using Linux
> 
> Did you find the answer? I also can't find where my notes are stored, without configuring sync.

You can check `config.json` under the `~/.config/Beaver-notes`.

**Comment by Dialga** [comment]
> > > Sorry, what folder? I checked in `/home/tio/.config/Beaver-notes/` even in the Synch path folder. I cannot seem to find the files.
> > > Note: I am using Linux
> > 
> > 
> > Did you find the answer? I also can't find where my notes are stored, without configuring sync.
> 
> You can check `config.json` under the `~/.config/Beaver-notes`.

Thanks for the answer, but this answer should be more prominently documented, who would think that all notes are being stored in a config file?
