### ISSUE TITLE
Linux App don't start after upgrade to version 2.3.0

### ISSUE THREAD

**Issue by eag75** [Daniele-rolli/Beaver-Notes#40]
**Bug Description**
Hi Daniele,
the Linux app no longer starts after the update to version 2.3. The following error message is displayed on startup.

APPIMAGE env is not defined, current application is not an AppImage
checkForUpdatesAndNotify called, downloadPromise is null
APPIMAGE env is not defined, current application is not an AppImage
checkForUpdatesAndNotify called, downloadPromise is null

The app window only shows a white background.

From the Git repository the app can be started (with yarn) in the current version, so I suspect that something went wrong when creating the rpm package. I also tried to uninstall the app once and reinstall it with the rpm package, but the app still doesn't start properly.

**To Reproduce**
1. Start the App on Terminal or from menu
2. The error message appear and the show a white blank screen.

**Screenshots**
![Bildschirmfoto vom 2023-12-31 12-44-00](https://github.com/Daniele-rolli/Beaver-Notes/assets/155111097/b71fc509-5936-418b-9ab7-35b592d8ed11)

**Desktop (please complete the following information):**
- Device Specification: [AMD Ryzan 5, Nvidia Geforce RTX 3060] 
- OS: [Fedora 39, rpm package x86_64]
- Application Version: [2.3.0]

Best regards
Danny

**Comment by Daniele-rolli** [comment]
Thanks for pointing that out, it has already been taken care of. Try reinstalling; it should work now.

**Comment by eag75** [comment]
Thank you! Reinstall does the trick! 😅

**Comment by Daniele-rolli** [comment]
No problem at all! I hope you enjoy the latest version and have a happy New Year!
