### ISSUE TITLE
Translation for "headingtree" is a little weird

### ISSUE THREAD

**Issue by bigshans** [Daniele-rolli/Beaver-Notes#43]
"Headingtree" sounds strange and I've never heard it before. When I checked the Italian translation, it is "Ricerca intestazioni" which Google translated to mean "header search.". I think there might be something wrong here, and I believe "heading search" would be a better choice.

**Comment by Daniele-rolli** [comment]
Well, it might sound a little weird, but in the end, it employs the same logic as words like ‘family tree.’ However, for the sake of clarity, I’ll probably change it. Thanks for pointing that out.

**Comment by bigshans** [comment]
> Well, it might sound a little weird, but in the end, it employs the same logic as words like ‘family tree.’ However, for the sake of clarity, I’ll probably change it. Thanks for pointing that out.

I‘m not familiar with "family tree". Maybe you mean "outline”?

**Comment by Daniele-rolli** [comment]
Look, a family tree is a type of diagram that illustrates relationships between people. It essentially depicts all the generations of a family in a tree-like diagram. In the Heading tree the term 'tree' is used because it showcases headings in a diagram, similar to the branches of a tree, extending from the principal heading to the subheadings.

**Comment by bigshans** [comment]
> Look, a family tree is a type of diagram that illustrates relationships between people. It essentially depicts all the generations of a family in a tree-like diagram. In the Heading tree the term 'tree' is used because it showcases headings in a diagram, similar to the branches of a tree, extending from the principal heading to the subheadings.

Oh, I see. But I often called this structure like "outline" or "TOC". I don't care that it looks like a tree, but rather that it functions.
![图片](https://github.com/Daniele-rolli/Beaver-Notes/assets/26884666/9ec3ce2a-2a5f-4a77-ac59-ccff522b6b96)

**Comment by Daniele-rolli** [comment]
I guess I’ll change it to make it clearer. We could simply call it ‘heading search,’ as you suggested. How does that sound?

**Comment by bigshans** [comment]
> I guess I’ll change it to make it clearer. We could simply call it ‘heading search,’ as you suggested. How does that sound?

I think it's great.

**Comment by Daniele-rolli** [comment]
Ok, I've just fixed it
