### ISSUE TITLE
bug, enabling and disabling focus mode hides side menu

### ISSUE THREAD

**Issue by dmeatte-aq** [Daniele-rolli/Beaver-Notes#5]
Clicking the focus mode button and then pressing escape to exit the mode makes the menu on the left side disappear. It will reappear if the app is restarted.

**Comment by Daniele-rolli** [comment]
Hey, thanks for pointing that out. However, this is actually not a bug, but a feature. When you press 'esc', you exit the full window mode, not the focus mode. By hovering the cursor over the blank part on top of the title, the editor menu will appear, and you'll notice that the focus mode is still active. If you need any clarification, I'll leave this issue open for a bit so you can reply.

**Comment by dmeatte-aq** [comment]
I see what you did now.  While it may not be a bug as it's what you intended, it confused me and was very much not what I was expecting. Escape is a key I expect to use to exit or back out of a choice. In this case, it was a partial back out, and it wasn't clear to me that focus mode was intentionally still turned on.

It looks like you're targeting your  product towards an audience that is more interesting in writing words instead of code, I would sugest either making far more obvious that focus mode is still on in the UI (I did find the top menu on my own), or making a second escape exit it completely would have prevented me from having a UX issue. As a user, I didn't realize what state the app was in at that time and is was confusing.

On a different note, this looks like a really cool take on the markdown editor. It feels like a fully local version of Confluence. The editing experience is nice and does what I expect. I'm looking forward to seeing how you evolve it in the future.

**Comment by Daniele-rolli** [comment]
I will work on making the focus mode status more obvious in the UI for version 0.0.7, which is upcoming. 

Thanks for your interest in the project, I hope you'll enjoy your note taking experience.
