### ISSUE TITLE
Auto Sync 

### ISSUE THREAD

**Issue by mrlinnth** [Daniele-rolli/Beaver-Notes#54]
**Is your feature request related to a problem? Please describe.**
I am sure many users will forget to click the export/import buttons for the sync after editing the notes.

**Describe the solution you'd like**
Periodically syncing or upon page transition will be nice.

**Describe alternatives you've considered**
If auto sync is not easy to implement, maybe a reminder dialog box when opening the app or existing the app to do the import/export.

This is really an amazing product and I really appreciate the hard works.

**Comment by Daniele-rolli** [comment]
Hey there! Regarding auto-sync, I've already tinkered with it. It would require rewriting part of Beaver Notes, which isn't ideal since the current system works. However, I suppose a pop-up reminding the user to import/export data upon opening the app could do it. The pop-up would only appear if a sync path is set up, and users could still disable it in settings if they find it annoying. What do you think of this?

**Comment by mrlinnth** [comment]
Thanks for a quick response. Yea a confirmation popup for those using sync and a toggle to enable it sounds great.

**Comment by Daniele-rolli** [comment]
Hey there, this issue will be closed next week with the release of version 2.5.0, as indicated by commits eeb36ed159768a1463dd69cc6dfd88d96176f71b and 505004cbec56de018e5367fa175d3a8ae9d6885b. The only remaining task is the implementation of the simplified Chinese translation for the new feature, which will likely be completed during the week. 

P.S. This release will be slightly delayed to avoid having three releases within a few days of each other.

**Comment by bigshans** [comment]
> Hey there, this issue will be closed next week with the release of version 2.5.0, as indicated by commits eeb36ed159768a1463dd69cc6dfd88d96176f71b and 505004cbec56de018e5367fa175d3a8ae9d6885b. The only remaining task is the implementation of the simplified Chinese translation for the new feature, which will likely be completed during the week. 
> 
> P.S. This release will be slightly delayed to avoid having three releases within a few days of each other.

OK, I'll check tonight.
