### ISSUE TITLE
Some questions about style

### ISSUE THREAD

**Issue by bigshans** [Daniele-rolli/Beaver-Notes#71]
1. In dark mode, code block comments are not distinguishable from the background.
2. The line height of list seems to be a little high. I compare with tiptap's live demo, and their lists seem to be not as high.

![图片](https://github.com/Daniele-rolli/Beaver-Notes/assets/26884666/5f9b1a35-3801-48c5-8a2c-da0486cfb600)
![图片](https://github.com/Daniele-rolli/Beaver-Notes/assets/26884666/0a35e6ea-5666-420a-a693-6387c5c81363)

**Comment by Daniele-rolli** [comment]
Thanks for reporting these issues. I’ll delve into them this afternoon, though they seem like an easy fix that will surely make its way into 2.6.0.

**Comment by Daniele-rolli** [comment]
I've reduced the padding a bit between editor components and fixed the code block; however, the padding heavily depends on @Tailwind/Typography.

<img width="1018" alt="Screenshot 2024-01-14 at 2 06 00 PM" src="https://github.com/Daniele-rolli/Beaver-Notes/assets/67503004/721f7ab5-4445-4b92-bab5-bd7e7555f4e0">

**Comment by bigshans** [comment]
It's better than before.
Well, I like more compact layout personally but someone maybe don't. Can line height be adjustable?

**Comment by bigshans** [comment]
> I've reduced the padding a bit between editor components and fixed the code block; however, the padding heavily depends on @Tailwind/Typography.
> <img alt="Screenshot 2024-01-14 at 2 06 00 PM" width="1018" src="https://private-user-images.githubusercontent.com/67503004/296551707-721f7ab5-4445-4b92-bab5-bd7e7555f4e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyNDAzMjYsIm5iZiI6MTcwNTI0MDAyNiwicGF0aCI6Ii82NzUwMzAwNC8yOTY1NTE3MDctNzIxZjdhYjUtNDQ0NS00YjkyLWJhYjUtYmQ3ZTc1NTVmNGUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE0VDEzNDcwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhNjMxZmEwMDBkYmM3YTExM2M1ZmNiMGQ3ZmY5ZjgzNDA0ZWI2ZmJkOTY5OWIxZGNiMzc1ZWIyYzYyODQzMmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AwocM5TpemxHATeOYIWeOtmg62fWumGQ06SBpBLFyw8">

Well, it's also acceptable. Thanks for your amazing work!
