### ISSUE TITLE
Request to close spellchecker

### ISSUE THREAD

**Issue by bigshans** [Daniele-rolli/Beaver-Notes#81]
Now spellchecker is a little annoying to run anywhere such as codeblock. I think if we can't control it's behavior, maybe closing it is a better choice.

![图片](https://github.com/Daniele-rolli/Beaver-Notes/assets/26884666/3144ce64-cf4e-47bb-a4c0-c6350179bc88)

**Comment by Daniele-rolli** [comment]
Look, I understand that spellcheck might be annoying, but many people rely on it, so removing it is not an option. I'll look into the issue, but as of now, I cannot replicate it on my Mac. If you could share more information about the OS you're using, it would help us better understand and address this issue.

**Comment by bigshans** [comment]
> Look, I understand that spellcheck might be annoying, but many people rely on it, so removing it is not an option. I'll look into the issue, but as of now, I cannot replicate it on my Mac. If you could share more information about the OS you're using, it would help us better understand and address this issue.

I encounter this problem at Arch Linux and Windows 10.

And I think if you want to keep spellchecker, you need to provide some options to configure it, such as dictionary or switch. Most of time, it works very poor for my language and I hardly use it.

**Comment by bigshans** [comment]
> Look, I understand that spellcheck might be annoying, but many people rely on it, so removing it is not an option. I'll look into the issue, but as of now, I cannot replicate it on my Mac. If you could share more information about the OS you're using, it would help us better understand and address this issue.
> 
> EDIT: After looking into it, we actually don't use spellcheck at all; it's all handled by the system, if I'm not mistaken.

On Windows and Linux this is powered by Hunspell dictionaries, and on macOS it makes use of the native spellchecker APIs.

**Comment by Daniele-rolli** [comment]
Okay, I think we could solve this fairly quickly by adding a toggle to settings to either disable or enable spellcheck. What do you think?

**Comment by bigshans** [comment]
> Okay, I think we could solve this fairly quickly by adding a toggle to settings to either disable or enable spellcheck. What do you think?

I think it's great.

**Comment by Daniele-rolli** [comment]
I have been attempting for a couple of hours to get this working, but it's nearly impossible. I will continue trying; however, if we are unable to set the value from the settings, what do you suggest we do?

**Comment by Daniele-rolli** [comment]
After much tweaking, I have concluded that spell check, unfortunately, is here to stay. There is no actual way to allow the user to turn it on or off. Therefore, I'm labeling this issue as "won't fix."
