### ISSUE TITLE
Add a control to adjust the global font size in notes

### ISSUE THREAD

**Issue by barry-denby** [Daniele-rolli/Beaver-Notes#85]
Have recently discovered Beaver Notes and I'm pretty impressed with it has an application. This is not a bug but more of a feature enhancement. I believe it would be useful if there was a global control/setting to adjust the font size of notes.

i.e. if the global font size is increased it increases the size of regular text, headings, and code samples. similar if decreased.

**Comment by Daniele-rolli** [comment]
Hey there, thanks for the suggestion. I'd like to start by pointing out that Beaver Notes has been built using Tailwind Typography, meaning that the fonts are adaptive to the device screen size. Therefore, implementing an adaptable font size would require rewriting the app. However, a suitable alternative could be implementing three or four options for the interface size, which would enlarge or reduce both the interface and fonts, similar to what macOS offers in the display settings. Something like this could be implemented in the settings:
![Image 1-23-24 at 2 24 PM](https://github.com/Daniele-rolli/Beaver-Notes/assets/67503004/f9cb1b9d-8ce8-4642-b211-ca3f9d887e54)

**Comment by barry-denby** [comment]
Wasn't expecting that to be addressed that quickly. Thanks for implementing it.

**Comment by Daniele-rolli** [comment]
You're welcome; I do my best to keep every member of our community happy.
