### ISSUE TITLE
Leave some space at the end of editor

### ISSUE THREAD

**Issue by bigshans** [Daniele-rolli/Beaver-Notes#92]
There is no remaining space at the bottom of the editor. Therefore, when the notes reach the bottom people must put their sight at the bottom of the screen. This makes people feel uncomfortable. Because when people browse the web, their sights are often in the middle of the screen. They have to bow their heads when the sight is too low.

![图片](https://github.com/Daniele-rolli/Beaver-Notes/assets/26884666/caa79db8-6926-4dd5-837c-f54c3fe28673)

**Comment by Daniele-rolli** [comment]
Got you, I've added a 1.5 rem padding to the bottom which should be enough to solve this issue. It ends up looking like this
![Screenshot 2024-01-25 at 6 35 44 PM](https://github.com/Daniele-rolli/Beaver-Notes/assets/67503004/6796cae0-6053-440f-8cfd-963c88065b8d)
