### ISSUE TITLE
Missing vim mode/keybindings

### ISSUE THREAD

**Issue by paullotz** [Daniele-rolli/Beaver-Notes#98]
There is no problem, but Beaver-Notes lacks the obligatory Vim keybings/mode :).

Solution: Implement a toggleable Vim mode to improve the overall feeling when writing notes.

**Comment by Daniele-rolli** [comment]
While I see the potential of Vim keybindings, incorporating a toggleable Vim mode might complicate the minimalist design of Beaver-Notes. However, we can consider adding specific, non-intrusive shortcuts inspired by Vim to enhance the user experience without sacrificing simplicity. Would you be able to share which shortcuts would be most useful for you?
